# Default values for rocketmq-k8s-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

broker:
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent
    repository: "automqinc/rocketmq"
    tag: "5.1.3-alpine"

  partition: 0
  persistence:
    enabled: false
    size: 8Gi

  nameOverride: "broker"
  fullnameOverride: ""
  namesrvAddr: ""

  conf:
    clusterNameOverride: ""
    brokerNamePrefixOverride: ""
  
  config: ""

  service:
    port: 8081

  jvmMemory: " -Xms4g -Xmx4g -Xmn2g -XX:MaxDirectMemorySize=8g "
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 2
      memory: 4Gi

  nodeSelector: { }

  tolerations: [ ]

  s3stream:
    s3WALPath: "/tmp/s3rocketmq/wal"
    s3Endpoint: "http://minio.hellocorp.test"
    s3Bucket: "wxy"
    s3Region: "us-east-1"
    s3ForcePathStyle: true
    s3AccessKey: "Y6pKg2MmFL3wlWiEJEtc"
    s3SecretKey: "eTWpQEutpExoYXebV8D1HXJ8TwDWyoKoAVJpX32K"


  db:
    url: "jdbc:mysql://10.1.0.119:3306/metadata"
    userName: "root"
    password: "root"


