apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rocketmq-broker.fullname" . }}
spec:
  replicas: {{ .Values.broker.replicaCount }}
  selector:
    matchLabels:
      {{- include "rocketmq-broker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rocketmq-broker.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: broker
          image: {{ include "rocketmq-broker.brokerImage" . }}
        {{- if $.Values.broker.image.pullPolicy }}
          imagePullPolicy: {{ $.Values.broker.image.pullPolicy }}
        {{- end }}
          command: [ "/bin/sh" ]
          args: [ "-c", "./run-server.sh com.automq.rocketmq.broker.BrokerStartup -c /home/rocketmq/rocketmq-on-s3-5.1.3/conf/$(INSTANCE_NAME)-$(CLUSTER_NAME)" ]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CLUSTER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/cluster']
            - name: INSTANCE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/name']
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: BROKER_MEM
              value: {{ .Values.broker.jvmMemory }}
          ports:
            - name: broker
              containerPort: 8081
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 15
            successThreshold: 1
            tcpSocket:
              port: 8081
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 15
            successThreshold: 1
            tcpSocket:
              port: 8081
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.broker.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /home/rocketmq/rocketmq-on-s3-5.1.3/conf
              name: broker-config
            - mountPath: /root/logs/rocketmqlogs
              name: broker-storage
      {{- with .Values.broker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: broker-config
          configMap:
            name: broker-conf
        - name: broker-storage
          hostPath:
            path: /root/logs/rocketmqlogs
            type: DirectoryOrCreate
